### ISSUE TITLE
Wandering Trader spawn caused server crash

### ISSUE THREAD

**Issue by shanethegooner** [Kim-Lan/strong-leads#5]
Firstly, this is a great mod, and it worked well on my 1.21.10 Fabric server until today. I was AFKing a farm and came back to a crashed server. Starting the server and logging back in would instantly crash it again. 

From the crash report, I assume a Wandering Trader spawned, one of its llamas got snagged on something, and the trader moved too far from the llama, which in vanilla would snap the lead, but with the mod, it didn't. 

Disabling the mod and booting the server up again thankfully fixed it. 

```
Description: Ticking entity

java.lang.NoSuchMethodError: 'net.minecraft.class_243 net.minecraft.class_1297.method_19538()'
	at knot//net.minecraft.class_9817.wrapOperation$ckk000$strong-leads$wrapSnapLongLeash(class_9817.java:525)
	at knot//net.minecraft.class_9817.method_60965(class_9817.java:162)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:617)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:427)
	at knot//net.minecraft.class_1308.method_5670(class_1308.java:304)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:558)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2695)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:363)
	at knot//net.minecraft.class_1496.method_5773(class_1496.java:595)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:796)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:416)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:386)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1138)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3748(class_3176.java:321)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:775)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:297)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_9817.wrapOperation$ckk000$strong-leads$wrapSnapLongLeash(class_9817.java:525)
	at knot//net.minecraft.class_9817.method_60965(class_9817.java:162)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:617)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:427)
	at knot//net.minecraft.class_1308.method_5670(class_1308.java:304)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:558)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2695)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:363)
	at knot//net.minecraft.class_1496.method_5773(class_1496.java:595)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:796)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:416)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:trader_llama (net.minecraft.class_3986)
	Entity ID: 6
	Entity Name: Trader Llama
	Entity's Exact location: -1108.55, 70.00, 3925.45
	Entity's Block location: World: (-1109,70,3925), Section: (at 11,6,5 in -70,4,245; chunk contains blocks -1120,-64,3920 to -1105,319,3935), Region: (-3,7; contains chunks -96,224 to -65,255, blocks -1536,-64,3584 to -1025,319,4095)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:416)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:386)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1138)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3748(class_3176.java:321)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:775)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:297)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; class_3222{name=shanethegooner, id=52, pos=(-1108.699999988079, 71.0, 3922.300000011921), mode=SURVIVAL, permission=4}
	Chunk stats: 1272, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1024,68,3045), Section: (at 0,4,5 in -64,4,190; chunk contains blocks -1024,-64,3040 to -1009,319,3055), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,-64,2560 to -513,319,3071)
	Level time: 51562524 game time, 54755292 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 51236 (now: false), thunder time: 66969 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 52
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1840)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1141)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:1021)
	at knot//net.minecraft.class_3176.method_3748(class_3176.java:321)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:775)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:297)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by Kim-Lan** [comment]
I have no plans to support 1.21.10 right now, but I just updated the mod to 26.1.x so hopefully the issue is resolved on those versions.
